### ISSUE TITLE
TypeError - no implicit conversion of Array into String in V0.4.4

### ISSUE THREAD

**Issue by Alexdelgadodiaz** [leavez/cocoapods-binary#100]
Thanks for your feedback!

If it's a bug:

- What's your environment:
  - run ` pod env | egrep 'CocoaPods |Xcode|cocoapods-binary' ` then paste the result here 
- A demo project is helpful:
  - It will be very helpful if provides a demo project that reproduce the problem. A blank project with cocoapods-binary can be downloaded [here](https://github.com/leavez/cocoapods-binary/files/3086250/BinaryDemo.zip), which can be remodeled to a minimal problematic environment. Attach the demo.zip to the comments.

`# Uncomment the next line to define a global platform for your project

platform :ios, '13.1'

plugin 'cocoapods-binary'
use_frameworks!
enable_bitcode_for_prebuilt_frameworks!
#keep_source_code_for_prebuilt_frameworks!
all_binary!

target 'targetExample' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for targetExample
  pod 'TGCoreiOS', :git => 'https://inblabla@bla.git', :branch => 'development'

end`

`{19-10-23 21:21}MBP-de-adiaz:~/Documents/workspace/NewTry/MyProject/targetExample2/TGExample2@master✗✗✗✗✗✗ adiaz% pod install
🚀  Prebuild frameworks
Analyzing dependencies
Pre-downloading: `TGCoreiOS` from `https://intelinovasoftware.visualstudio.com/TRAININGYM/_git/TG%20Core%20iOS`, branch `development`
Downloading dependencies
Installing Bolts (1.9.0)
Installing Parse (1.17.3)
Installing TGCoreiOS (0.1.0)
Generating Pods project
Prebuild frameworks (total 3)
Prebuilding Bolts...
Prebuilding Parse...
Prebuilding TGCoreiOS...

🤖  Pod Install
Analyzing dependencies
Pre-downloading: `TGCoreiOS` from `https://intelinovasoftware.visualstudio.com/TRAININGYM/_git/TG%20Core%20iOS`, branch `development`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/Cellar/cocoapods/1.8.4/libexec/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15 (19A582a)
       Xcode : 11.1 (11A1027)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 8cd584af0762c38d884e651a61c7f999addf250d
               trunk - CDN - https://cdn.cocoapods.org/
               visualstudio-trainingym-_git-tg%20core%20ios - git - https://intelinovasoftware.visualstudio.com/TRAININGYM/_git/TG%20Core%20iOS @ 29622d37f5d5edfd774d5b5f905f56c65c90e998
```

### Plugins

```
cocoapods-binary      : 0.4.4
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project

platform :ios, '13.1'

plugin 'cocoapods-binary'

use_frameworks!
enable_bitcode_for_prebuilt_frameworks!
#keep_source_code_for_prebuilt_frameworks!
all_binary!


target 'TGExample2' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for targetExample
  pod 'TGCoreiOS', :git => 'https://intelinovasoftware.visualstudio.com/TRAININGYM/_git/TG%20Core%20iOS', :branch => 'development'
#  pod 'TGCore', :git => 'https://github.com/Alexdelgadodiaz/mypod.git'
end

#post_install do |installer|
#     installer.pods_project.targets.each do |target|
#         target.build_configurations.each do |config|
#             config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
#             config.build_settings['ENABLE_BITCODE'] = 'YES'
#         end
#     end
# end
```

### Error

```
TypeError - no implicit conversion of Array into String
/Library/Ruby/Gems/2.6.0/gems/cocoapods-binary-0.4.4/lib/cocoapods-binary/Integration.rb:176:in `+'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-binary-0.4.4/lib/cocoapods-binary/Integration.rb:176:in `block (2 levels) in <class:Installer>'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-binary-0.4.4/lib/cocoapods-binary/Integration.rb:150:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-binary-0.4.4/lib/cocoapods-binary/Integration.rb:150:in `block in <class:Installer>'
/usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
/usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.8.4/libexec/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.8.4/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.8.4/libexec/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.
`

**Comment by ikesyo** [comment]
Looks like this is a duplicate of #50.

**Comment by Alexdelgadodiaz** [comment]
But it seems like that bug is solved already. Is it hapeening again?

**Comment by ikesyo** [comment]
#50 is still open (reopened).

**Comment by lixiaoyu** [comment]
@ikesyo  Hello i meet similar issues too,have you solve it yet? It seem that  not the same with #50 

Error log like this 
`

### Error

```
TypeError - no implicit conversion of Array into String
/Users/yuli/Desktop/CICD/cocoapods-binary-cache/lib/cocoapods-binary-cache/pod-binary/integration.rb:240:in `+'
/Users/yuli/Desktop/CICD/cocoapods-binary-cache/lib/cocoapods-binary-cache/pod-binary/integration.rb:240:in `block (2 levels) in <class:Installer>'
/Users/yuli/Desktop/CICD/cocoapods-binary-cache/lib/cocoapods-binary-cache/pod-binary/integration.rb:212:in `each'
/Users/yuli/Desktop/CICD/cocoapods-binary-cache/lib/cocoapods-binary-cache/pod-binary/integration.rb:212:in `block in <class:Installer>'
/Users/yuli/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
/Users/yuli/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
/Users/yuli/.rvm/gems/ruby-2.4.1/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/yuli/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Users/yuli/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/Users/yuli/.rvm/gems/ruby-2.4.1/bin/pod:23:in `load'
/Users/yuli/.rvm/gems/ruby-2.4.1/bin/pod:23:in `<main>'
/Users/yuli/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:24:in `eval'
/Users/yuli/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:24:in `<main>'`

The affect code is 
`     # to remove the resurce bundle target. 
                # When specify the "resource_bundles" in podspec, xcode will generate a bundle 
                # target after pod install. But the bundle have already built when the prebuit
                # phase and saved in the framework folder. We will treat it as a normal resource
                # file.
                # https://github.com/leavez/cocoapods-binary/issues/29
                if spec.attributes_hash["resource_bundles"]
                    bundle_names = spec.attributes_hash["resource_bundles"].keys
                    spec.attributes_hash["resource_bundles"] = nil 
                    spec.attributes_hash["resources"] ||= []
                    spec.attributes_hash["resources"] += bundle_names.map{|n| n+".bundle"}
                end`
