### ISSUE TITLE
CocoaPods 1.6.0 or above are not supported for resource-containing static frameworks

### ISSUE THREAD

**Issue by ikesyo** [leavez/cocoapods-binary#50]
I got an error when running with CocoaPods 1.7.0.beta.2:

```
TypeError - no implicit conversion of Array into String
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-binary-0.4.2/lib/cocoapods-binary/Prebuild.rb:131:in `basename'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-binary-0.4.2/lib/cocoapods-binary/Prebuild.rb:131:in `block (2 levels) in prebuild_frameworks!'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-binary-0.4.2/lib/cocoapods-binary/Prebuild.rb:129:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-binary-0.4.2/lib/cocoapods-binary/Prebuild.rb:129:in `map'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-binary-0.4.2/lib/cocoapods-binary/Prebuild.rb:129:in `block in prebuild_frameworks!'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-binary-0.4.2/lib/cocoapods-binary/Prebuild.rb:118:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-binary-0.4.2/lib/cocoapods-binary/Prebuild.rb:118:in `prebuild_frameworks!'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-binary-0.4.2/lib/cocoapods-binary/Prebuild.rb:206:in `block in <class:Installer>'
```

Looks like this is due to the change for `Pod::PodTarget#resource_paths`

- doc: https://www.rubydoc.info/gems/cocoapods/Pod%2FPodTarget:resource_paths
- A PR which introduced the change: https://github.com/CocoaPods/CocoaPods/pull/7820
  - The method now returns `[Hash{String=>Array<String>}]` over `[Array<String>]`
  - Included since 1.6.0.beta.1.
- Affected code: https://github.com/leavez/cocoapods-binary/blob/9f40c5df4149598b03b44c01d33b04e78ff38772/lib/cocoapods-binary/Prebuild.rb#L120-L130

Could you take a look? Thanks in advance!

**Comment by ikesyo** [comment]
@leavez Thanks for the quick fix! 💖

**Comment by leavez** [comment]
I found some changes in copying resources in cocoapods 1.7 for static framework. The resource coping still not work.

https://github.com/CocoaPods/CocoaPods/issues/8573#issuecomment-476970611

**Comment by leavez** [comment]
I found there's a change in copying resource files for static framework in cocoapods 1.7. 

When building a pod with 'static_framework = true' and with cocoapods 1.6, it will generate a framework containing the resource files in framework bundle. But when use cocoapods 1.7, no resources will copied to the framework bundle. 

This plugin cannot handle the change right not. So It doesn't work in cocoapods 1.7

**Comment by reuvenlevitsky** [comment]
Hey @leavez ,
Thanks for your amazing work!

Is there any estimation for a fix for cocoapods 1.7 static frameworks with bundle?

**Comment by KPR7168** [comment]
do we have a solution for this yet?

**Comment by bolee** [comment]
not support resources now?
